server:
  port: 8769
spring :
  application:
     name : config-server
  cloud :
    config :
      server:
        git:
          uri: https://github.com/itcast132465/hello
          searchPaths: cong			                      #远程仓库的文件夹地址
          username: itcast132465			                  #登录名
          password: itcast132465			                  #密码
          label: master		  		                      #Git仓库的分支名
          basedir:
management:             				#暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

